### ISSUE TITLE
Linky Ou Gazpar ? 

### ISSUE THREAD

**Issue by aladin2000** [beufanet/gazpar#3]
Je te signale un 'copier/coller'   dans ton readme de manière cohérente avec tes fichier de paramétres 
> GRANT ALL ON "gazpar" TO "gazpar" ?  plutôt que linky dans ce qui suit//// 

Create d
```
> CREATE DATABASE gazpar
> CREATE USER "gazpar" WITH PASSWORD [REDACTED]
> GRANT ALL ON "gazpar" TO "linky"

**Comment by beufanet** [comment]
Fixé, merci pour la remontée
