### ISSUE TITLE
libxslt.so.1:

### ISSUE THREAD

**Issue by aladin2000** [beufanet/gazpar#4]
Hi 
could it be possible to have a lool on that error and how to fix it ? ( I did it out of docker ) 
thanks  ... 

 python3 gazinflux.py --days=5
......
Traceback (most recent call last):
  File "gazinflux.py", line 12, in <module>
    import gazpar
  File "/home/pi/gazparinflux/gazpar.py", line 29, in <module>
    from lxml import etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

What I have done to fix it ....    
apt install  python-libxslt1  
and change LD_LIBRARY_PATH to include Docker Lib 
LD_LIBRARY_PATH=/var/lib/docker/overlay2/*******802/diff/usr/lib:.

**Comment by beufanet** [comment]
Can you explain if you're using native python or docker version ? I think you should install python3-lxml and not xslt ?

**Comment by beufanet** [comment]
no feedbacks
